### ISSUE TITLE
Sammeln bestehende Unterlagen

### ISSUE THREAD

**Issue by fabianhauser** [openhsr/linux-workshop#2]
- https://gitlab.ethz.ch/thealternative/courses
  - Diverse Linux-Related Workshop Unterlagen, inkl. Linux Einführung

**Comment by se-na** [comment]
https://drive.switch.ch/index.php/s/ssu8Q2r67CYlZul?path=%2FBetriebssysteme%201
BSYS Tutorial

**Comment by fabianhauser** [comment]
@se-na hat bei The-Alternative noch die LaTeX-sourcen der Anleitungen angefragt.
