### ISSUE TITLE
Termin finden

### ISSUE THREAD

**Issue by se-na** [openhsr/linux-workshop#3]
2. -3. Woche Frühlingssemester
Terminclash (Teilzeit, andere Events, ..)
Todo

- [x] Info Vorstand
- [x] Raum reservation (Steckdosen)
- [x] Essen (Sandwich) / Getränk
- [x] USB (für Instalation)
- [x] Backup (info oder etwas anbieten)

**Comment by fabianhauser** [comment]
Wie wäre es mit Dienstag, 3. März sowie Dienstag, 10. März jeweils 17:00-~20:00, @se-na  und @FunkyFabe ?
Ich habe nicht so ganz den Überblick bei den Teilzeitstudenten, wenn ich es richtig gesehen habe, sind die meisten im zweiten Semester am Dienstag da.

**Comment by se-na** [comment]
Ja
