### ISSUE TITLE
Rund-Mail

### ISSUE THREAD

**Issue by se-na** [openhsr/linux-workshop#4]
([Inhaltlich vermutlich ähnlich wie E-Mail betr. Git-Workshop](https://github.com/openhsr/git-github-workshop/issues/6))

Inhaltspunkte:

- [x] Backup
- [x] Doodle mit begrenzter Teilnehmerzahl (E-Mail-Adresse für Vorbereitungsinstruktionen angeben)
- [x] Bei vollen Workshops / Terminkollision und Interesse bitte ein E-Mail an info@openhsr.ch
- [x] Nur für open\HSR Mitglieder kostenfrei zugänglich (Mitgliedschaft im open\HSR Ebenfalls kostenfrei - Link auf Mitglied-werden-E-Mail)
- [x] Helfer mit Linux-Kenntnissen gesucht

**Comment by se-na** [comment]
Email:
> Liebe Mitstudentin, lieber Mitstudent
> 
> Wir hoffen, du bist gut in das neue Semester gestartet!
> Hast du schon Mal von Linux gehört und möchtest es näher kennenlernen - oder hast du Linux schon ausprobiert und hättest gerne etwas Orientierungshilfe?
> 
> 
> Wir möchten dir helfen, in der Linux-Welt Fuss zu fassen, und bieten deshalb neu einen Linux-Installationskurs und einen Linux-Basics-Kurs an. Die beiden Kurse können unabhängig voneinander besucht werden, sind aber lose aufeinander aufbauend.
> 
> Die Teilnahme ist selbstverständlich kostenlos und beinhaltet einen Snack offeriert vom open\HSR - einzige Voraussetzung für die Teilnahme ist eine Vereinsmitgliedschaft ([was ebenfalls kostenlos und unkompliziert ist](mailto:info@openhsr.ch?subject=Mitglied%20werden&body=Hallo%20Zusammen!%0A%0AIch%20w%C3%BCrde%20gerne%20Mitglied%20im%20open%5CHSR%20werden!%0A%0AMein%20Github%20Benutzername%20lautet%20%5BGITHUB%20Benutzername%5D.%0A%5BFalls%20du%20keinen%20Github%20Account%20hast%2C%20kannst%20du%20diesen%20Absatz%20l%C3%B6schen%5D%0A%0ALiebe%20Gr%C3%BCsse%2C%0A%5BNAME%5D)) 🙂
> 
> ## Kurs *Linux Installation* - Dienstag, 10. März 2020 17:00-~20:00 Uhr
> Im Installationskurs helfen dir unsere Linux-Experten bei der Installation auf deinem Laptop. Dazu gehört natürlich auch das Vorbereiten für den Studienalltag (Skripte-Server, Listen mit empfohlenen Programmen, etc.).
> [Hier mit E-Mail-Adresse anmelden (Anmeldungen sind verbindlich, damit wir die richtige Menge Snacks sicherstellen können!)](https://doodle.com/poll/hzc7frirah4nmt2a)
> 
> Wichtig: Erstelle vor der Teilnahme Zuhause ein Back-Up deiner Daten - sicher ist sicher!
> 
> ## Kurs *Linux Basics* - Dienstag, 17. März 2020 17:00-~20:00 Uhr
> Der Linux Basics-Kurs bietet dir einen einfachen Praxiseinstieg in den Umgang mit Linux.
> Willkommen sind alle mit installiertem Linux oder mit einer vorbereiteten Linux VM.
> Zu Beginn erhältst du einen Überblick über die Linux-Welt und anschliessend lernst du interaktiv die wichtigsten Commandline-Befehle.
> [Hier mit E-Mail-Adresse anmelden (Anmeldungen sind verbindlich, damit wir die richtige Menge Snacks sicherstellen können!)](https://doodle.com/poll/35h78s9hmam3e67f)
> 
> ----
> Die Teilnehmerzahl bei beiden Kursen ist beschränkt. First Come, First Served!
> 
> Dein open\HSR
> 
> PS: Du hast schon Erfahrung mit Linux? Wir suchen noch nach Helfern - bitte antworte einfach auf dieses E-Mail!

**Comment by se-na** [comment]
@fabianhauser das wäre der Entwurf für das Rund-Mail. Passt das?

**Comment by fabianhauser** [comment]
@se-na danke für den Entwurf!

Ich habe noch ein paar Dinge etwas angepasst, die Daten aktualisiert und die Doodle-Links erstellt.
Passt das so für dich?

**Comment by se-na** [comment]
Ja alles bestens

**Comment by fabianhauser** [comment]
@openhsr/vorstand  kann ich das E-Mail so rauslassen? Mein Vorschlag wäre, es an *stud.i, stud.wing, stud.m, stud.eeu, stud.e, studmse.all* zu senden.

**Comment by Darnor** [comment]
Passt. :+1:
