### ISSUE TITLE
Kursinhalt

### ISSUE THREAD

**Issue by se-na** [openhsr/linux-workshop#5]

**Comment by se-na** [comment]
@fabianhauser Ich habe einige Dokumente zu den Kurs-Inhalten erstellt. Aber den Inhalten ist nicht zutrauen, da ich diese selber eigentlich nicht verstehe. Einige Punkte sind auch noch offen und deshalb ist es Wichtig, dass es noch Linux kenner anschauen. Vielleicht magst auch du?

**Comment by fabianhauser** [comment]
Super, danke für die Programme @se-na, sieht schon sehr gut aus!
Ich habe noch ein paar Punkte in der Übersicht ergänzt bzw. weggelassen (z.B. Environment Variablen), da mich diese für den ersten Einstieg nicht so relevant dünken.

Könntest du mal schauen, was du davon hältst?

Ich würde gar nicht zu viel im Programm beschreiben, sondern dann gleich Slides erstellen (so sparen wir uns etwas Arbeit 😉)
