### ISSUE TITLE
Haftungsausschluss

### ISSUE THREAD

**Issue by se-na** [openhsr/linux-workshop#8]

**Comment by das-g** [comment]
Vorschlag (zum Ausdrucken)

> Um am Linux-Installationskurs teilzunehmen, bestätige ich &ndash; die / der unterzeichnete Teilnehmer\*in &ndash; folgendes:
>
> ### Awareness
>
> Ich bin mir bewusst:
>
> - [ ] Eine Betriebssystem-Installation ist stets mit **Risiken** für das betroffene Gerät und die darauf befindlichen Daten verbunden.
>
> ### Backup vorhanden
> 
> Das Gerät, auf dem ich Linux installieren werde
> - [ ] ist fabrikneu und enthält daher **keine Daten**, die ich behalten möchte.
> &mdash; _oder_ &mdash;
> - [ ] enthält ausschliesslich Daten, von denen ich auf einem **separaten** Datenträger ein **vollständiges und aktuelles Backup** habe.
> &mdash; _oder_ &mdash;
> - [ ] enthält keine Daten, deren Verlust ein Problem wäre.
> ### Haftungs-Ausschluss
> 
> - [ ] **Meine Kursteilname erfolgt auf eigenes Risiko.** Insbesondere haften weder der Verein open\HSR noch die Organisator\*innen, Kursleiter\*innen oder sonstige am Kurs beteiligte (inkl. anderer Teilnehmenden) für
>     - **Verlust von Daten** auf meinem Gerät
>        - Dies umschliesst auch Einstellungen, Software, etc.
>     - **sonstige Schäden** an meinem Gerät (z.B. an der Hardware)
> 
>     selbst falls diese fahrlässig herbeigeführt wurden.
> 
> Für mutwillige Beschädigungen und grobfahrlässige Beschädigungen haftet die/der jeweilige Verursacher\*in.
> 
> Teilnehmer\*in: ____________________
> 
> Ort & Datum: Rapperswil, 2020-03-10
> 
> Unterschrift: ____________________
